'''
Name		:final_proj_test_image_now.py
Author		:Puneet Bansal and Amogh Shrikhande

References 	:
			MySQL link : https://pimylifeup.com/raspberry-pi-mysql/  
			Python MYSql link : https://www.w3schools.com/python/python_mysql_create_db.asp
			primary key :http://www.mysqltutorial.org/mysql-primary-key/
			python: https://www.geeksforgeeks.org/python-programming-language/
'''
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fetch_imag_data = QtWidgets.QPushButton(self.centralwidget)
        self.fetch_imag_data.setGeometry(QtCore.QRect(80, 120, 191, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fetch_imag_data.setFont(font)
        self.fetch_imag_data.setObjectName("fetch_imag_data")
        self.correct_image_op = QtWidgets.QLineEdit(self.centralwidget)
        self.correct_image_op.setGeometry(QtCore.QRect(150, 190, 71, 32))
        self.correct_image_op.setObjectName("correct_image_op")
        self.wrong_image_op = QtWidgets.QLineEdit(self.centralwidget)
        self.wrong_image_op.setGeometry(QtCore.QRect(380, 190, 71, 32))
        self.wrong_image_op.setObjectName("wrong_image_op")
        self.correct_image = QtWidgets.QLabel(self.centralwidget)
        self.correct_image.setGeometry(QtCore.QRect(90, 190, 68, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.correct_image.setFont(font)
        self.correct_image.setObjectName("correct_image")
        self.wrong_image = QtWidgets.QLabel(self.centralwidget)
        self.wrong_image.setGeometry(QtCore.QRect(320, 190, 68, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.wrong_image.setFont(font)
        self.wrong_image.setObjectName("wrong_image")
        self.correct_voice = QtWidgets.QLabel(self.centralwidget)
        self.correct_voice.setGeometry(QtCore.QRect(90, 350, 68, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.correct_voice.setFont(font)
        self.correct_voice.setObjectName("correct_voice")
        self.correct_voice_op = QtWidgets.QLineEdit(self.centralwidget)
        self.correct_voice_op.setGeometry(QtCore.QRect(150, 350, 71, 32))
        self.correct_voice_op.setObjectName("correct_voice_op")
        self.fetch_voice_command_data = QtWidgets.QPushButton(self.centralwidget)
        self.fetch_voice_command_data.setGeometry(QtCore.QRect(80, 260, 211, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fetch_voice_command_data.setFont(font)
        self.fetch_voice_command_data.setObjectName("fetch_voice_command_data")
        self.wrong_voice = QtWidgets.QLabel(self.centralwidget)
        self.wrong_voice.setGeometry(QtCore.QRect(320, 350, 68, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.wrong_voice.setFont(font)
        self.wrong_voice.setObjectName("wrong_voice")
        self.wrong_voice_op = QtWidgets.QLineEdit(self.centralwidget)
        self.wrong_voice_op.setGeometry(QtCore.QRect(380, 350, 71, 32))
        self.wrong_voice_op.setObjectName("wrong_voice_op")
        self.last_image_taken = QtWidgets.QPushButton(self.centralwidget)
        self.last_image_taken.setGeometry(QtCore.QRect(90, 500, 391, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.last_image_taken.setFont(font)
        self.last_image_taken.setObjectName("last_image_taken")
        self.magi_wand_title = QtWidgets.QLabel(self.centralwidget)
        self.magi_wand_title.setGeometry(QtCore.QRect(220, 50, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.magi_wand_title.setFont(font)
        self.magi_wand_title.setObjectName("magi_wand_title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 190, 68, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 350, 68, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 350, 68, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 190, 68, 22))
        self.label_4.setObjectName("label_4")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(60, 550, 451, 221))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../Downloads/SampleJPGImage_50kbmb.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.get_latest_label = QtWidgets.QPushButton(self.centralwidget)
        self.get_latest_label.setGeometry(QtCore.QRect(80, 430, 201, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.get_latest_label.setFont(font)
        self.get_latest_label.setObjectName("get_latest_label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 430, 191, 32))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fetch_imag_data.setText(_translate("MainWindow", "Fetch Image Data"))
        self.correct_image.setText(_translate("MainWindow", "Correct:"))
        self.wrong_image.setText(_translate("MainWindow", "Wrong:"))
        self.correct_voice.setText(_translate("MainWindow", "Correct:"))
        self.fetch_voice_command_data.setText(_translate("MainWindow", "Fetch Voice Command Data"))
        self.wrong_voice.setText(_translate("MainWindow", "Wrong:"))
        self.last_image_taken.setText(_translate("MainWindow", "Last Image Taken"))
        self.magi_wand_title.setText(_translate("MainWindow", "MAGIC WAND"))
        self.label.setText(_translate("MainWindow", "%"))
        self.label_2.setText(_translate("MainWindow", "%"))
        self.label_3.setText(_translate("MainWindow", "%"))
        self.label_4.setText(_translate("MainWindow", "%"))
        self.get_latest_label.setText(_translate("MainWindow", "Get Latest Label"))

