# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practiceDesign.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
import pyqtgraph as pg
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GetValueButton = QtWidgets.QPushButton(self.centralwidget)
        self.GetValueButton.setGeometry(QtCore.QRect(10, 40, 121, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.GetValueButton.setFont(font)
        self.GetValueButton.setObjectName("GetValueButton")
        self.labelTempOutput_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelTempOutput_1.setGeometry(QtCore.QRect(410, 10, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelTempOutput_1.setFont(font)
        self.labelTempOutput_1.setObjectName("labelTempOutput_1")
        self.labelHumidOutput_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelHumidOutput_1.setGeometry(QtCore.QRect(700, 10, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.labelHumidOutput_1.setFont(font)
        self.labelHumidOutput_1.setObjectName("labelHumidOutput_1")
        self.labelTimestampOut_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelTimestampOut_1.setGeometry(QtCore.QRect(200, 10, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelTimestampOut_1.setFont(font)
        self.labelTimestampOut_1.setObjectName("labelTimestampOut_1")
        self.lineEditTempThreshold = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTempThreshold.setGeometry(QtCore.QRect(100, 190, 113, 32))
        self.lineEditTempThreshold.setObjectName("lineEditTempThreshold")
        self.lineEditHumidThreshold = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHumidThreshold.setGeometry(QtCore.QRect(100, 250, 113, 32))
        self.lineEditHumidThreshold.setObjectName("lineEditHumidThreshold")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 170, 211, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 230, 211, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Timestamp = QtWidgets.QLabel(self.centralwidget)
        self.Timestamp.setGeometry(QtCore.QRect(270, 380, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.Timestamp.setFont(font)
        self.Timestamp.setObjectName("Timestamp")
        self.Temperature = QtWidgets.QLabel(self.centralwidget)
        self.Temperature.setGeometry(QtCore.QRect(490, 380, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.Temperature.setFont(font)
        self.Temperature.setObjectName("Temperature")
        self.Humidity = QtWidgets.QLabel(self.centralwidget)
        self.Humidity.setGeometry(QtCore.QRect(720, 380, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.Humidity.setFont(font)
        self.Humidity.setObjectName("Humidity")
        self.Status = QtWidgets.QLabel(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(80, 380, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.Status.setFont(font)
        self.Status.setObjectName("Status")
        self.SetThresholdButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetThresholdButton.setGeometry(QtCore.QRect(100, 130, 121, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SetThresholdButton.setFont(font)
        self.SetThresholdButton.setObjectName("SetThresholdButton")
        self.Alarm = QtWidgets.QLabel(self.centralwidget)
        self.Alarm.setGeometry(QtCore.QRect(80, 321, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.Alarm.setFont(font)
        self.Alarm.setObjectName("Alarm")
        self.labelTimestampOut = QtWidgets.QLineEdit(self.centralwidget)
        self.labelTimestampOut.setGeometry(QtCore.QRect(140, 40, 231, 32))
        self.labelTimestampOut.setObjectName("labelTimestampOut")
        self.labelTempOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.labelTempOutput.setGeometry(QtCore.QRect(380, 40, 241, 32))
        self.labelTempOutput.setObjectName("labelTempOutput")
        self.labelHumidOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.labelHumidOutput.setGeometry(QtCore.QRect(630, 40, 231, 32))
        self.labelHumidOutput.setObjectName("labelHumidOutput")
        self.DisplayAlarm = QtWidgets.QLineEdit(self.centralwidget)
        self.DisplayAlarm.setGeometry(QtCore.QRect(200, 320, 471, 32))
        self.DisplayAlarm.setObjectName("DisplayAlarm")
        self.DisplayCurrentValue_Status = QtWidgets.QLineEdit(self.centralwidget)
        self.DisplayCurrentValue_Status.setGeometry(QtCore.QRect(20, 410, 191, 32))
        self.DisplayCurrentValue_Status.setObjectName("DisplayCurrentValue_Status")
        self.DisplayCurrentValue_Timestamp = QtWidgets.QLineEdit(self.centralwidget)
        self.DisplayCurrentValue_Timestamp.setGeometry(QtCore.QRect(230, 410, 221, 32))
        self.DisplayCurrentValue_Timestamp.setText("")
        self.DisplayCurrentValue_Timestamp.setObjectName("DisplayCurrentValue_Timestamp")
        self.DisplayCurrentValue_Humid = QtWidgets.QLineEdit(self.centralwidget)
        self.DisplayCurrentValue_Humid.setGeometry(QtCore.QRect(670, 410, 211, 31))
        self.DisplayCurrentValue_Humid.setObjectName("DisplayCurrentValue_Humid")
        self.DisplayCurrentValue_Temp = QtWidgets.QLineEdit(self.centralwidget)
        self.DisplayCurrentValue_Temp.setGeometry(QtCore.QRect(470, 410, 181, 32))
        self.DisplayCurrentValue_Temp.setObjectName("DisplayCurrentValue_Temp")
        self.radioButton_Temp = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Temp.setGeometry(QtCore.QRect(320, 220, 119, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Temp.setFont(font)
        self.radioButton_Temp.setObjectName("radioButton_Temp")
        self.radioButton_Humid = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Humid.setGeometry(QtCore.QRect(320, 250, 119, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Humid.setFont(font)
        self.radioButton_Humid.setObjectName("radioButton_Humid")
        self.Celsius_farenhiet = QtWidgets.QPushButton(self.centralwidget)
        self.Celsius_farenhiet.setGeometry(QtCore.QRect(310, 100, 151, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Celsius_farenhiet.setFont(font)
        self.Celsius_farenhiet.setObjectName("Celsius_farenhiet")
        self.Temp_units = QtWidgets.QLineEdit(self.centralwidget)
        self.Temp_units.setGeometry(QtCore.QRect(530, 0, 31, 32))
        self.Temp_units.setObjectName("Temp_units")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 170, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.graphics_graph = pg.PlotWidget(self.centralwidget)
        #self.graphics_graph = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphics_graph.setGeometry(QtCore.QRect(20, 490, 871, 192))
        self.graphics_graph.setObjectName("graphics_graph")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 100, 20, 191))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(57, 283, 211, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(260, 100, 20, 191))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(60, 90, 211, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(60, 120, 211, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 100, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(300, 170, 16, 121))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(310, 280, 141, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(310, 160, 151, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(450, 170, 16, 121))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(310, 190, 151, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.output_window = QtWidgets.QLineEdit(self.centralwidget)
        self.output_window.setGeometry(QtCore.QRect(490, 120, 241, 141))
        self.output_window.setObjectName("output_window")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 460, 68, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 90, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GetValueButton.setText(_translate("MainWindow", "Get Values"))
        self.labelTempOutput_1.setText(_translate("MainWindow", "TEMPERATURE"))
        self.labelHumidOutput_1.setText(_translate("MainWindow", "HUMIDITY"))
        self.labelTimestampOut_1.setText(_translate("MainWindow", "TIME STAMP"))
        self.label.setText(_translate("MainWindow", "Temperature Threshold Input"))
        self.label_2.setText(_translate("MainWindow", "HumidityThreshold Input"))
        self.Timestamp.setText(_translate("MainWindow", "TIMESTAMP"))
        self.Temperature.setText(_translate("MainWindow", "TEMPERATURE"))
        self.Humidity.setText(_translate("MainWindow", "HUMIDITY"))
        self.Status.setText(_translate("MainWindow", "STATUS"))
        self.SetThresholdButton.setText(_translate("MainWindow", "SetThresholds"))
        self.Alarm.setText(_translate("MainWindow", "ALARM MESSAGE:"))
        self.radioButton_Temp.setText(_translate("MainWindow", "Temperature"))
        self.radioButton_Humid.setText(_translate("MainWindow", "Humidity"))
        self.Celsius_farenhiet.setText(_translate("MainWindow", "F-C/C-F"))
        self.label_3.setText(_translate("MainWindow", "SELECT GRAPH"))
        self.label_4.setText(_translate("MainWindow", "THRESHOLD"))
        self.label_6.setText(_translate("MainWindow", "GRAPH"))
        self.label_5.setText(_translate("MainWindow", "Output Window"))

